### ISSUE TITLE
Usage: How should I type two `app`s differently? What about TypeScript?

### ISSUE THREAD

**Issue by dizys** [flarum/types#1]
"Simply install dependency in your extension frontend's package.json" seems not to be working for visual studio code.

Could anyone please enlighten me about exactly how I should use this types package to make two different `app`s in `src/admin` and `src/forum` typed accordingly?

Moreover, what should I do if I'm using TypeScript to write extension frontend? `import {app} from 'flarum/admin'` seems not to be working since `flarum/*` is just types and nothing concrete.

Lots of thanks!

**Comment by dizys** [comment]
My current solution is to create two `types.d.ts` files:

`js/src/admin/types.d.ts`:

```ts
import AdminApp from 'flarum/admin/AdminApplication';

declare global {
  const app: AdminApp;
}
```

`js/src/forum/types.d.ts`:

```ts
import ForumApp from 'flarum/forum/ForumApplication';

declare global {
  const app: ForumApp;
}
```

Not very elegant, but it works, for both JavaScript and TypeScript. 🤣

**Comment by davwheat** [comment]
You should be importing `app` from `flarum/forum/app`, or from `flarum/admin/app`.

This package is now out of date and will be deprecated. You should use our new TS Config package instead.
